name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/profile.jpg
    - assets/buslogo.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf